### ISSUE TITLE
Add a MAX_NUMBER_OF_CONNECTIONS for NS_UA_WS

### ISSUE THREAD

**Issue by willyaranda** [telefonicaid/notification_server#42]
We do not want to accept new connections if we have reached a MAX_NUMBER_OF_CONNECTIONS.

We need to decide if we set that number from some constants (ulimit? ram? cpu?) or it's up to the deployer.

**Comment by frsela** [comment]
Also we should manage ulimit range from node. Since it isn't only a POSIX based framework, we need a library hack:

@see: http://stackoverflow.com/questions/8141057/can-i-set-ulimit-from-node-js
@see: https://github.com/joyent/node/pull/2143

We shall validate this library or directly call the ulimit command using child_process library:
http://nodejs.org/api/child_process.html
